gateway-service/src/main/resources/configs/common/application.conf
- kube adds default env as `ATTRIBUTE_SERVICE_PORT`, so adding suffix `_CONFIG` for app related host/port config.
=> avoids name conflicts with default kube env names

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcher.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcherTests.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/EntityServiceTest.java
This reverts a minor part of d1659f49898fe3f0c46c24b4d2d359b219ed4ab0. The old behavior is to use groupBy on the entity id and count the records, which is what this commit gets back again.
In the long run, we should get entity total from EDS instead.
=> Reverting the optimization to use DISTINCTCOUNT for entity total query.

gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/TheRestGroupRequestHandler.java, gateway-service-impl/src/test/resources/expected-test-responses/explore/aggregations-with-groupby-and-the-rest.json, gateway-service-impl/src/test/resources/expected-test-responses/explore/aggregations-with-multiple-groupbys-and-the-rest.json, gateway-service-impl/src/test/resources/query-service-requests-and-responses/explore/aggregations-with-groupby-and-the-rest.json, gateway-service-impl/src/test/resources/query-service-requests-and-responses/explore/aggregations-with-multiple-groupbys-and-the-rest.json, gateway-service/src/main/resources/configs/common/application.conf
Include Rest only outputs a single aggregated result as Others. Having an order by without group by is not supported by the current OLAP store (Pinot)
=> fix(explore): include rest should not order by

helm/templates/service.yaml, helm/values.yaml
Istio does protocol selection by looking at
the prefix of port name defined in the service.
In case istio is not able to detect the protocol,
it treats the traffic as plain tcp traffic.
=> Add name for the port in service

helm/templates/deployment.yaml
Portname was updated to grpc by defining `containerPortName` in values.yaml. Updated the liveness probe with the new value.
=> Update the port for liveness probe

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcher.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/SelectionAndFilterNode.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcherTests.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/EntityServiceTest.java
is grouping by multiple columns since that leads to wrong results.
For now we set limit to a higher value in those cases.
=> Don't set limit for the entities query when the query to OLAP

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/converters/QueryAndGatewayDtoConverter.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcher.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/transformer/RequestPreProcessor.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilder.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/SelectionAndFilterNode.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/SelectionNode.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/SortAndPaginateNode.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionContextBuilderVisitor.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitor.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/EntitiesRequestAndResponseUtils.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/QueryServiceRequestAndResponseUtils.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/converter/GatewayValueToQueryValueConverterTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcherTests.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/transformer/RequestPreProcessorTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/EntityServiceTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilderTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitorTest.java, gateway-service-impl/src/test/resources/configs/request-preprocessor-test/domains-config.conf
**Why this PR?**
This PR is fixing a bug in entity queries, which causes the query layer to error out when a query is asking for entity attributes that span across the EDS and QueryService data sources, in the case there is no data for that entity in QueryService.
**What's the fix?**
Currently, the query federation code that we have (see https://github.com/hypertrace/gateway-service/tree/main/gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query) doesn't treat the timestamp predicates in the query like other regular predicates. The timestamps are special cased and they're added to the upstream requests only when the query is being sent to a remote service. That's what caused the above mentioned bug.
This PR treats the timestamp predicates, just like any other …
=> Timestamp filter refactoring to fix time range filtering bugs in entity queries.

.snyk, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcher.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/transformer/RequestPreProcessor.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/util/TimeRangeFilterUtil.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/EntitiesRequestContext.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/EntityService.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionContext.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilder.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitor.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/QueryServiceRequestAndResponseUtils.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/datafetcher/EntityDataServiceEntityFetcherTests.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcherTests.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/transformer/RequestPreProcessorTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/EntitiesRequestResponseProcessorTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/EntityServiceTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilderTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitorTest.java
This is fixing a bug where the time range wasn't being passed to query service in the query service requests. You can say this was a bug introduced as part of https://github.com/hypertrace/gateway-service/pull/44 bug fix.
Unit testing, tested in real setup and verified that all the query service queries have time range now.
No functional changes and bug was introduced in this release itself.
=> fix: Fixing a bug in query execution, which wasn't passing the time range in filter to query service.

.circleci/config.yml
Reverts hypertrace/gateway-service#43
@JBAhire Unfortunately, I've to revert this PR because i've run into the failures like https://app.circleci.com/pipelines/github/hypertrace/gateway-service/246/workflows/eb93b6a6-5465-46d8-832d-174c2f49223b/jobs/718 when charts are being published on release. 
I see that @aaron-steinfeld had some comments on https://github.com/hypertrace/attribute-service/pull/30 and probably you can raise this PR again after addressing the same questions on this PR too?
=> Revert "updates release workflow"

gateway-service/src/main/resources/configs/common/application.conf
The scope filters are added per scope, based on the domainobject configs defined here https://github.com/hypertrace/gateway-service/blob/main/gateway-service/src/main/resources/configs/common/application.conf#L43
The scope filter added for `API_TRACE` being https://github.com/hypertrace/gateway-service/blob/main/gateway-service/src/main/resources/configs/common/application.conf#L81, were not getting applied, since there were no attribute id mappings defined for the `API_TRACE` scope and hence, the API traces returned did not have the `apiBoundaryType = ENTRY` applied on them
Tested end to end manually
=> fix: added missing api_trace id mapping

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/transformer/ResponsePostProcessor.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/EntityService.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/transformer/ResponsePostProcessorTest.java
Entities are requested with various selections, metrics and time series data. There can be cases when a selection(or metric or time series) requested does not exist on the Entity
Instead of returning no data at all for the selections, add a default value for the missing selection. Because, you should always return what you requested for, be it a valid value or a missing value
Specifically, needed for https://github.com/hypertrace/gateway-service/pull/53 and https://github.com/hypertrace/gateway-service/issues/54, because time agnostic APIs might not have attributes, metrics or time series data in the requested time range
Tested end to end by running services locally, and unit tests
=> fix(entities): add missing selections, aggregations or time series

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/baseline/BaselineServiceImpl.java
In time series data timestamps of metric series and baseline metric series are not matching, baseline startTime and endTime also aligned with nearest period boundary to match timestamps.
Local testing done and its working.
=> Fix align both metricseries timestamps and baseline series timestamps

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionContext.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitor.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/ExecutionContextTest.java
Filter maps in Execution Context was being built incorrectly
Added unit tests and verified end to end
=> fix(entities): incorrect source to filter expression map

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilder.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/visitor/FilterOptimizingVisitor.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilderTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/visitor/FilterOptimizingVisitorTest.java
Entities request was failing if the selections were both on EDS and QS, but filters and order by are on QS. The reason for failure being the AndNode/OrNode in `FilterOptimizingVisitor`assumes that the children can only be DataFetcherNode and nothing else, but since we were pushing pagination down to QS, it also had a `PaginateOnlyNode` on top of `DataFetcherNode`
Added unit tests
=> fix(entities): selections on eds, and filters/order by on qs

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/converters/StringToAttributeKindConverter.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/converter/StringToAttributeKindConverterTest.java
This changes the behavior when querying for a string array that is returned as null from query service. Currently, such a case causes a NPE and fails the query as proto does not support setting nulls. With this change, we now convert nulls into empty lists, which is the same behavior we have for the empty string and seems overall consistent.
Verified this with an e2e query, also added unit test.
=> fix: when a list is returned as null, convert it to empty

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/comparators/ValueComparator.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/comparators/ValueComparatorTest.java
The previous implementation of array ordering errored if arrays were mismatched in length. This change updates the ordering to a fairly standard lexicographical sort. This is implemented using guava, and the description there describes the behavior:
> Returns a new comparator which sorts iterables by comparing corresponding elements pairwise until a nonzero result is found; imposes "dictionary order." If the end of one iterable is reached, but not the other, the shorter iterable is considered to be less than the longer one. For example, a lexicographical natural ordering over integers considers [] < [1] < [1, 1] < [1, 2] < [2].
https://guava.dev/releases/snapshot/api/docs/com/google/common/collect/Comparators.html#lexicographical-java.util.Comparator-
Verified e2e with data of different …
=> fix: implement array value lexicographical comparator

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/baseline/BaselineServiceImpl.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/baseline/BaselineServiceImplTest.java
Aligning timestamp not required for Aggregation data, its only needed for time series data. 
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
=> Aligning time not required aggregationData

gateway-service-api/src/main/proto/org/hypertrace/gateway/service/v1/entities.proto
Added a flag to fetch total number of entities. If the flag is set, the total number of entities will be fetched from the data store, else ignored
The actual implementation will come as a separate PR https://github.com/hypertrace/gateway-service/pull/76 to make the change backward compatible, because the current clients assume that the total number of entities will always be fetched. 
Hence, the clients need to change first using the latest Gateway Service API
No testing required, since it's just a proto API change
=> chore(entities-api): flag to fetch total entitiess

gateway-service-api/src/main/proto/org/hypertrace/gateway/service/v1/entities.proto, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/DataFetcherNode.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilder.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitor.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/visitor/FilterOptimizingVisitor.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitorTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/visitor/FilterOptimizingVisitorTest.java
Total number of entities should only be fetched, if requested by the client
Added unit test
=> perf(entities): fetch total entities, only if requested

.snyk, gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/EntityService.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/ExploreService.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/span/SpanService.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/trace/TracesService.java
- Remove usage of deprecated methods from Platformregistry metrics library in support of using micrometer library
- Using prefix - `hypertrace` - for all metrics for consistency
Tested locally using docker-compose (see notes below)
will update the existing documentation referring to metrics and dashboards - https://github.com/hypertrace/hypertrace/tree/main/kubernetes/monitoring
=> refactor: using micrometer based metrics and consistent with its names

.snyk, gateway-service-api/build.gradle.kts, gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/TimeAggregationsRequestHandler.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/explore/TimeAggregationsRequestHandlerTest.java, gateway-service/build.gradle.kts
Add support for explicitly declaring the ordering of an explorer time series query. Previously, it was always assumed to be ascending with time.
Added UT
=> fix: add support for reversing explore time series request

gateway-service-api/build.gradle.kts, gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilder.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilderTest.java, gateway-service/build.gradle.kts, gateway-service/src/main/resources/configs/common/application.conf
Queries hitting QS assumed that pagination is pushed down to QS (_based on some condition_), but `QueryServiceEntityFetcher` has an inherent check which hardcodes the limit to 10K, if there are more than 1 group bys on the request
That means, even if there was a limit in the entities request, it was not honored, and all the entities were returned in the response. 
Fixed by limiting the results in memory
Added unit tests and e2e locally
=> fix(entities): limit entities result in memory for QS

gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/datafetcher/EntityDataServiceEntityFetcher.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/datafetcher/EntityDataServiceEntityFetcherTests.java
Time range was being applied on entity service queries even if it was requested as time agnostic
Added UTs
=> fix: omit time range on time agnostic entity query

.snyk, gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/util/ExpressionReader.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionContext.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilder.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeUtils.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/ExecutionContextTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeUtilsTest.java, gateway-service/build.gradle.kts
A selection attribute in entities request can be present in multiple sources. That results in non deterministic response, since the attribute is present in multiple sources, it can be returned from either of the sources, leading to non determinism in the response
The fix is to request unique set of attributes across sources, based on the pivot source. The pivot source being EDS, in case of time agnostic entities request, else the pivot source being QS by default
Added unit tests. And, tested the UI screens manually
=> fix(entities): request unique set of attributes across sources

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/AttributeMetadataProvider.java, gateway-service/build.gradle.kts
Iterating over a grpc stream partially results in memory leak both on server-side and client-side. Fixing it by completing the iteration.
Tested manually. 
NA
=> Netty OOM fix

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcher.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/span/SpanService.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/trace/TracesService.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcherTests.java
Limit total agg queries that only expect a single result. Allows better query validation on QS side.
=> refactor: add limit on total queries

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/entity/EntityRequestHandler.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/explore/entity/EntityRequestHandlerTest.java
Handle empty entity id scenario in explore query
Added unit test
=> Handle empty entity id scenario

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/ExploreRequestContext.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/RequestHandler.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/entity/EntityRequestHandler.java
Attribute Metadata was always missing for explore queries, leading to any value type, being displayed as string. The correct way is to convert attribute metadata map into `resultKeyToAttributeMetadataMap`, like https://github.com/hypertrace/gateway-service/blob/2255fd7c49a42a2f81fccaee1b8574feb4136cd5/gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/datafetcher/QueryServiceEntityFetcher.java#L92
=> fix(explore): missing attribute kind, due to incorrect metadata map

gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/RequestHandler.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/TimeAggregationsRequestHandler.java, gateway-service-impl/src/test/resources/query-service-requests-and-responses/explore/grouped-time-aggregation-with-group-limit-and-the-rest.json, gateway-service-impl/src/test/resources/query-service-requests-and-responses/explore/grouped-time-aggregation-with-group-limit.json, gateway-service-impl/src/test/resources/query-service-requests-and-responses/explore/time-aggregations-space-filtered.json, gateway-service-impl/src/test/resources/query-service-requests-and-responses/explore/time-aggregations.json
Fixed two issues in explorer
1. When processing results, metadata lookup was failing as it was assuming the result col name must be the attribute id, when it's actually the provided alias
2. Rather than over-limiting on TS queries, we limit to exactly the amount of returned results. I want to verify this is right, but my thinking is this is holdover from before we had separate group and row limits.
Updated and verified UTs, tested behavior e2e
=> refactor: reduce grouped time series explorer limit

gateway-service-api/src/main/proto/org/hypertrace/gateway/service/v1/explore.proto, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/ExploreService.java
Make `explore` query time range params optional
Ran modified version of service with graphql service and ran the query
- [ x ] My changes generate no new warnings
=> if no time range set use entity request handler

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/EntityService.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitor.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitorTest.java
Updated entity service to parallelize the query for total entity count as that is not required to perform other entity data query.
Unit tests
=> refactor: parallelize total entities query

gateway-service-factory/src/main/java/org/hypertrace/gateway/service/GatewayServiceFactory.java
This application config was previously initialized in the container code (?!), and was missed when we migrated containers ( https://github.com/hypertrace/gateway-service/commit/04e51b8657254f3d1966075cbe8c4d99c8cd9508#diff-8bf2eff6ecf87c5ce50dcc4bc191882f02fd44009aea35e7da4346a4e009ec25L36-L37 )
E2E on local
=> fix: restore removed config initialization

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/datafetcher/EntityDataServiceEntityFetcher.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/datafetcher/EntityDataServiceEntityFetcherTest.java
If the `includeInactive` flag is set to `true`, then `getEntities` query is skipping adding timestamp filters on entities, while fetching the results https://github.com/hypertrace/gateway-service/blob/07539521826daa6d6df9a846e50650021e5817b9/gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/datafetcher/EntityDataServiceEntityFetcher.java#L82
No such check exists while fetching the total. Timestamp filters are still getting added, even though the `includeInactive` flag is set to `true`. Hence, the inconsistency between entity results and total
Added unit tests. Verified e2e locally
=> fix(entities): include inactive entities total

gateway-service-api/src/main/proto/org/hypertrace/gateway/service/v1/gateway_query.proto, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/converters/QueryAndGatewayDtoConverter.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/converter/GatewayValueToQueryValueConverterTest.java
This PR renames the DISTINCT function type to DISTINCT_ARRAY. Making a breaking proto change as it is not being consumed anywhere yet.
=> chore: rename DISTINCT function type to DISTINCT_ARRAY

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/explore/RequestHandler.java, gateway-service-impl/src/test/resources/expected-test-responses/explore/group-by-with-offset.json, gateway-service-impl/src/test/resources/query-service-requests-and-responses/explore/group-by-with-offset.json, gateway-service-impl/src/test/resources/test-requests/explore/group-by-with-offset.json
Group by query with offset doesn't retrieve right results from pinot. So here are the changes done -
1. In case offset is provided with group by query, we just add offset to limit itself when querying Pinot. We will just skip the results(from Pinot) till offset when returning final results to the caller.
2. The rest group doesn't make sense with pagination scenario(query with offset). Such query will result in UnsupportedOperationException
3. Ideally for pagination case, no group limit should be specified. In case it is specified, we will use limit as min(limit, group-limit) + offset to query pinot.
=> fix: fix to handle group by with offset

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/EntityService.java, gateway-service/src/main/resources/configs/common/application.conf
Use different method to to get shorter string for logging
=> Use shorter string for debug logs

gateway-service-api/build.gradle.kts, gateway-service-factory/build.gradle.kts, gateway-service-impl/build.gradle.kts, gateway-service/build.gradle.kts, owasp-suppressions.xml
Updating dependencies, removing old suppressions.
=> chore: update dependencies

gateway-service-factory/build.gradle.kts, gateway-service-impl/build.gradle.kts, gateway-service/build.gradle.kts
updated service framework version to expose latency histogram metrics for grpc services
=> update service framework version
