gateway-service/build.gradle.kts
=> Update grpc utils with changes for binary headers

README.md
This PR adds,
- Hypertrace query architecture and explains working of gateway service in it's context.
- Build steps and image source for gateway service
=> Adds query architecture, build steps and image source in README

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitor.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/EntityServiceTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilderTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitorTest.java
Reverts hypertrace/gateway-service#39
=> Revert "Fixing a bug in merging the results from different data sources in ExecutionVisitor."

.circleci/config.yml
addresses https://github.com/hypertrace/hypertrace/issues/19 & https://github.com/hypertrace/hypertrace/issues/22
=> updates release workflow

.circleci/config.yml, build.gradle.kts, gateway-service/build.gradle.kts
addresses https://github.com/hypertrace/hypertrace/issues/19 & https://github.com/hypertrace/hypertrace/issues/22 
Please read discussion here: https://github.com/hypertrace/attribute-service/pull/30
=> updates release workflow and gradle plugin

.circleci/config.yml, build.gradle.kts, gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/converters/StringToAttributeKindConverter.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/converter/StringToAttributeKindConverterTest.java, gateway-service/build.gradle.kts
Fixing a bug in the code path when EDS returns an attribute value as a string but that needs to be converted into an array kind in gateway.
Unit testing.
Bug fix, no new feature. The title of the PR can be shown in the bug fixes if we were to include them in the release notes.
=> fix: Fixing an issue in converting EDS string to string array.

gateway-service-api/src/main/proto/org/hypertrace/gateway/service/v1/entities.proto, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/transformer/RequestPreProcessor.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilder.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/transformer/RequestPreProcessorTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/EntityServiceTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilderTest.java
See #54 for more details.
Tested end to end locally all the way from GQL by running the service locally
=> feat(entities): support for time agnostic apis

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/datafetcher/EntityDataServiceEntityFetcher.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilder.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/entity/query/visitor/ExecutionVisitor.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/datafetcher/EntityDataServiceEntityFetcherTests.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/entity/query/ExecutionTreeBuilderTest.java
fixes total number of entities fetched from EDS
=> fix: fetching total from EDS

.github/CODEOWNERS
Removing Buchi from CODEOWNERS.
=> Removing Buchi from CODEOWNERS.

gateway-service-baseline-lib/build.gradle.kts, gateway-service-baseline-lib/src/main/java/org/hypertrace/gateway/service/baseline/lib/BaselineCalculator.java, gateway-service-baseline-lib/src/test/java/org/hypertrace/gateway/service/baseline/lib/BaselineCalculatorTest.java, gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/baseline/BaselineServiceImpl.java, settings.gradle.kts
Ref issue : https://github.com/hypertrace/hypertrace-alert-engine/issues/54
=> Library for baseline calculation

.snyk, gateway-service-api/build.gradle.kts, gateway-service-baseline-lib/build.gradle.kts, gateway-service-impl/build.gradle.kts, gateway-service/build.gradle.kts
=> fix: update log4j

.idea/.gitignore, gateway-service-impl/build.gradle.kts, gateway-service/build.gradle.kts
Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
=> chore: update log4j version to 2.17.0

gateway-service-api/build.gradle.kts, gateway-service-baseline-lib/build.gradle.kts, gateway-service-baseline-lib/src/main/java/org/hypertrace/gateway/service/baseline/lib/BaselineCalculator.java, gateway-service-impl/build.gradle.kts, gateway-service/build.gradle.kts
Updating versions and general build cleanup
=> chore: build cleanup

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/GatewayServiceImpl.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/executor/QueryExecutorConfig.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/executor/QueryExecutorServiceFactory.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/span/SpanService.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/trace/TracesService.java, gateway-service-impl/src/test/resources/configs/gateway-service/application.conf, gateway-service/src/main/resources/configs/common/application.conf
Improve performance of trace and span queries by fetching the result rows and total in parallel.
Reverified unit, e2e tests
=> feat: parallelize span, trace total and event fetches

gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/util/AttributeMetadataUtil.java
Subpath attribute expressions were picking up the same value type/attribute kind as map, instead of primitive value types inside the map
Basically, if the query says 
```
url: selection(
expression: { key: "spanTags", subpath: "url" }
) {
value
}
```
the attribute kind for `url` becomes `TYPE_STRING_MAP`, since the attribute kind for `spanTags` is `TYPE_STRING_MAP`. This was leading to "Unable to read Map JSON String data" error, since the value for the subpath `url` isn't really a map
Tested end to end
=> fix(explore): subpath queries

gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/converters/StringToAttributeKindConverter.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/util/MetricAggregationFunctionUtil.java, gateway-service/build.gradle.kts
Adding support for MAX, MIN, SUM on timestamp
=> Support for MAX, MIN, SUM on timestamp 

gateway-service-factory/build.gradle.kts, gateway-service-impl/build.gradle.kts, gateway-service/build.gradle.kts
Update service framework version
=> chore: update framework versio

gateway-service-factory/build.gradle.kts, gateway-service-impl/build.gradle.kts, gateway-service/build.gradle.kts, gateway-service/src/main/java/org/hypertrace/gateway/service/GatewayServiceStarter.java
Update framework version and use new server building style.
=> chore: update service framework version

.github/workflows/pr-build.yml, build.gradle.kts
Please include a summary of the change, motivation and context.
added container scanning to gateway-service repo
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
=> added container scanning to gateway-service repo

gateway-service-api/src/main/proto/org/hypertrace/gateway/service/v1/gateway_query.proto
This PR adds support for DISTINCT aggregation selections.
Ran and tested locally.
=> feat: add DISTINCT function type

.github/workflows/dependency-check.yml, .github/workflows/merge-publish.yml, .github/workflows/pr-build.yml, .github/workflows/pr-test.yml, .github/workflows/publish.yml, build.gradle.kts, gateway-service-api/build.gradle.kts, gateway-service-api/src/main/proto/org/hypertrace/gateway/service/v1/gateway_query.proto, gateway-service-baseline-lib/build.gradle.kts, gateway-service-factory/build.gradle.kts, gateway-service-impl/build.gradle.kts, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/AttributeCacheKey.java, gateway-service-impl/src/main/java/org/hypertrace/gateway/service/common/converters/QueryAndGatewayDtoConverter.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/AttributeCacheKeyTest.java, gateway-service-impl/src/test/java/org/hypertrace/gateway/service/common/datafetcher/EntityInteractionsFetcherTest.java, gateway-service/build.gradle.kts, owasp-suppressions.xml
Exposing existing query service operator NOT_CONTAINS_KEY
=> feat: expose not contains key operator

gateway-service-api/src/main/proto/org/hypertrace/gateway/service/v1/spans.proto, gateway-service-api/src/main/proto/org/hypertrace/gateway/service/v1/traces.proto
Refere PR: https://github.com/hypertrace/gateway-service/pull/168/
Discussion: https://github.com/hypertrace/gateway-service/pull/168/#discussion_r1261211393
As part to support above change, we are following below to maintain backward compatibility:
- merge API changes
- update consumer to call new API
- merge the PR ( https://github.com/hypertrace/gateway-service/pull/168/) to provide implemenation.
Not Applicable
=> feat: update traces and spans apis
